; generated by PrusaSlicer 2.9.2 on 2025-06-10 at 19:46:01 UTC


; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

M73 P0 R2
M73 Q0 S2
M201 X7000 Y7000 Z200 E2500 ; sets maximum accelerations, mm/sec^2
M203 X400 Y400 Z12 E100 ; sets maximum feedrates, mm / sec
M204 P4000 R1200 T5000 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

;TYPE:Custom
M17 ; enable steppers
M862.3 P "XL" ; printer model check
M862.5 P2 ; g-code level check
M862.6 P"Input shaper" ; FW feature check
M115 U6.2.5+8912
G90 ; use absolute coordinates
M83 ; extruder relative mode
; set print area
M555 X142.589 Y4.056 W66.3991 H81.1195
; inform about nozzle diameter
M862.1 T0 P0.4 A0 F0
M862.1 T1 P0.4 A0 F0
M862.1 T2 P0.4 A0 F0
M862.1 T3 P0.4 A0 F0
M862.1 T4 P0.4 A0 F0

; turn on the heaters for every head and set the Temp to 175

M104 T0 S175
M104 T1 S175
M104 T2 S175
M104 T3 S175
M104 T4 S175


M217 Z2 ; set toolchange z hop to 2mm, or zhop variable from slicer if higher
; set bed and extruder temp for MBL
M140 S60 ; set bed temp
G0 Z5 ; add Z clearance
M109 T0 S175 ; wait for temp

; Home XY
G28 XY
; try picking tools used in print
G1 F24000

T1 S1 L0 D0
T2 S1 L0 D0
T3 S1 L0 D0
T4 S1 L0 D0
; select tool that will be used to home & MBL
T0 S1 L0 D0
; home Z with MBL tool
M84 E ; turn off E motor
G28 Z
G0 Z5 ; add Z clearance

M104 T0 S175 ; set idle temp
M190 S60 ; wait for bed temp

;G29 G ; absorb heat

M109 T0 S175 ; wait for temp

; move to the nozzle cleanup area
G1 X102 Y-2.944 Z5 F24000
M302 S160 ; lower cold extrusion limit to 160C
G1 E-2 F2400 ; retraction for nozzle cleanup
; nozzle cleanup
M84 E ; turn off E motor
G29 P9 X70 Y-2.944 W32 H7
G0 Z5 F480 ; move away in Z
M73 Q50 S1
M107 ; turn off the fan
; MBL
M84 E ; turn off E motor
G29 P1 ; invalidate mbl & probe print area
G29 P1 X30 Y0 W300 H20 C ; probe near purge place
G29 P3.2 ; interpolate mbl probes
G29 P3.13 ; extrapolate mbl outside probe area
G29 A ; activate mbl
G1 Z10 F720 ; move away in Z
G1 F24000
M73 P100 R0
P0 S1 L1 D0; park the tool